### ISSUE TITLE
'Use this template' Button missing?

### ISSUE THREAD

**Issue by Batres3** [AstroNvim/user_example#11]
As the title states, I can't seem to find the button, maybe it's a problem to do with my browser or something, I'm quite new to using github.

**Comment by utkarshgupta137** [comment]
You can just fork/clone the repo too

**Comment by mfmezger** [comment]
i can see it now. I think you can close the issue.

**Comment by mehalter** [comment]
I believe there was a bug in GitHub for a brief period of time. The button seems to be there again.

**Comment by Batres3** [comment]
Yep, all good now
