### ISSUE TITLE
Custom functions should be placed where? 

### ISSUE THREAD

**Issue by mantle2048** [AstroNvim/user_example#17]
For instance, I want to add a function that adds an `ipdb breakpoint` in python files and bind it in mapping.lua. Where should I elegantly position this function within the template?

**Comment by mehalter** [comment]
You can just add any sort of file that you want like `user/utils.lua` and then require it anywhere with `require "user.utils"`

**Comment by mantle2048** [comment]
I got it, thanks for your kind reply!
