### ISSUE TITLE
tagbar not working

### ISSUE THREAD

**Issue by chillin2** [AstroNvim/user_example#21]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1047+gf0f27e9ae

### Operating system/version

wsl

### Terminal/GUI

windows terminal

### Describe the bug

I installed the "preservim/tagbar" plugin but it doesn't work.

I added {  "preservim/tagbar" }, to my user.lua file.

I want to use tagbar, 

please check.

### Steps to Reproduce

{  "preservim/tagbar" },
:TagbarToggle

### Expected behavior

...

**Comment by mehalter** [comment]
Answered question in duplicate issue: https://github.com/AstroNvim/AstroNvim/issues/2214
