### ISSUE TITLE
Buffer visibly shifts on format with gitsigns on 

### ISSUE THREAD

**Issue by cordeliamin** [AstroNvim/user_example#6]
Operating System: Fedora Linux 37

Terminal: Kitty or Gnome Terminal

Description: When there are gitsigns markers present, the buffer will visibly shift side to side on format. It appears that the gitsigns markers are disappearing and loading back in, causing the movement.

Steps to reproduce:
- Remove/rename any existing user config
- Clone the user_example repository to the lua/ directory
- Rename user_example to user
- Open a file with a formatter active
- Make a change that needs to be formatted
- Format

Recording:
In the recording, I start with no user/ directory, so I'm using default AstroNvim. I open mappings.lua, add some unwanted whitespace, and run the formatter to see the expected behaviour of no shifting of the buffer.

Then, I rename user_example to user, repeat the above, and observe the bug. 

Finally, I open the same file which has been copied to a location not in a git repository, repeat the steps, and see the expected behaviour again.

[![asciicast](https://asciinema.org/a/XitL12bG5dcFeDCWCaXiapSrI.svg)](https://asciinema.org/a/XitL12bG5dcFeDCWCaXiapSrI)

**Comment by logan272** [comment]
Hey @cordeliamin , please take a look at this [PR](https://github.com/AstroNvim/user_example/pull/8). It may fix this issue.

**Comment by cordeliamin** [comment]
Hi there, I just got back to the PC I was facing the issue on, tried the most up to date version of this repo, and still face the issue. However, I have found on my laptop, where I cloned exactly the same user/ files from the original PC, I do not face the issue.

The original machine still has the problem with a complete reinstall of astronvim with the latest version of this repo.

**Comment by remcoros** [comment]
I had an issue where the gutter shifts shortly too when formatting, not sure if this is the same, but what helped for me was setting:
  
    signcolumn = "yes", -- sets vim.opt.signcolumn 

in options.lua

**Comment by utkarshgupta137** [comment]
I think you should probably open issues in the main repo, not here. By default, the gutter will change size depending on how many errors are present. If your LSP raises any formatting errors & those go away after formatting, then your gutter will shift. It is also possible that your LSP is momentarily reporting the errors while the file is being saved or buffer is updating.

**Comment by cordeliamin** [comment]
@remcoros 
This worked! Thanks!

@utkarshgupta137 
The issue happened even if the LSP didn't raise any formatting errors, for example in my recording in the original post. Adding some extra tabs or spaces doesn't cause any errors or warnings, but still has the issue. Conversely, if I cause the LSP to warn about a formatting issue which gets resolved on format, the issue does not return with the fix above.

I reported it here since it only happened for me when using this config, so I thought it was a configuration issue in here. If I have anything similar in the future, I'll raise in the main repo.
