### ISSUE TITLE
Provide an alternative single file example

### ISSUE THREAD

**Issue by academo** [AstroNvim/user_example#7]
Thanks for putting together this user_example.

I understand you favor a multiple file configuration but for many people this is not ideal and rather complex.

Could you please provide an example of a single file configuration?

**Comment by mehalter** [comment]
Check out the `single_file` branch!

**Comment by academo** [comment]
> `single_file`

Oh I completely missed that! could you add something in the README file about it? I don't usually go looking for branches or tags of repositories when reading docs.
