### ISSUE TITLE
Avoid overwriting Treesitter/Mason ensure_installed

### ISSUE THREAD

**Issue by patrickarmengol** [AstroNvim/user_example#9]
## Problem

Adding packages to `ensure_installed` in `plugins/treesitter.lua` and `plugins/mason.lua` overwrites the `ensure_installed` tables set by any astrocommunity packs. 

## Example

I have imported a few language packs in `plugins/community.lua`:
```
return {
  "AstroNvim/astrocommunity",

  -- colorschemes
  { import = "astrocommunity.colorscheme.catppuccin" },

  -- languages
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.lua" },
}
```

This results in the following being set in treesitter:
```
:TSConfigInfo
{
  ...
  ensure_installed = { "json", "jsonc", "toml", "markdown", "markdown_inline", "lua", "luap" },
  ...
}
```

But once I add something manually to `plugins/treesitter.lua` (following the commented out example):
```
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = { "python" },
  },
}
```

treesitter's ensure_installed is overwritten:
```
:TSConfigInfo
{
  ...
  ensure_installed = { "python" },
  ...
}
```

## Proposal

We could change the commented out examples in `plugins/treesitter.lua` and `plugins/mason.lua` to utilize [the util function used by astrocommunity to extend the ensure_installed list](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/utils.lua). This would risk confusing users, but would allow for interoperability between community packs and manual config. 

```lua
local utils = require "astrocommunity.utils"
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    if not opts.ensure_installed then
      opts.ensure_installed = {}
    elseif opts.ensure_installed == "all" then
      return
    end
    -- utils.list_insert_unique(opts.ensure_installed, { "python" })
  end
}
```

**Comment by mehalter** [comment]
Yeah I agree with this ! I will make an update soon. I also think that this might indicate the utility is useful enough to move out of Astrocommunity and just put in AstroNvim core as well. Seems like an anti pattern to use the function from the community just in case someone disables it. I will get something put together this week. Thanks for the recommendation!

**Comment by cybernet** [comment]
any updates ?

**Comment by mehalter** [comment]
Resolved in latest commit.
